---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
spec:
  blocks:
    - start: "${CILIUM_IP_POOL_START:-192.168.121.160}"
      stop: "${CILIUM_IP_POOL_STOP:-192.168.121.170}"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
spec:
  serviceSelector:
    matchLabels: {}
  nodeSelector:
    matchLabels: {}
  externalIPs: true
  loadBalancerIPs: true
  interfaces:
    - ^eth+
    - ^enp+
    - ^ens+
    - ^wlan+
    - ^vmbr+
