apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-auth
  namespace: flux-system
type: Opaque
stringData:
  username: admin
  password: "$2b$10$xeorWsB/w.ngj1HIxEaoMu0EdAe6TPB8RnfRXrHianUdib8vxvRlK"
